project:
  version: 1-0-0

server:
  port: 8989

spring:
  application:
    name: jpa-muli-datasource-${project.version}
  datasource:
    # 数据源-1，名称为 database1
    database1:
      username: savoidage
      password: 212121
      driverClassName: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://127.0.0.1:3306/jpa-muli-datasource-1?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    # 数据源-2，名称为 database2
    database2:
      username: savoidage
      password: 212121
      driverClassName: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://127.0.0.1:3306/jpa-muli-datasource-2?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8

  jpa:
    database: mysql
#    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect
